### ISSUE TITLE
Unit tests for comparing GEDCOM records.

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#10]
Anything that inherits from GedcomRecord must implement a function ( IsEquivalentTo ) that returns a true / false for matching a record against another.

For example, an individual might be matched against names, notes and dates.

This function is invoked from the base class Equals method. The primary use of this mechanism is to check that a database that has been loaded from a file, resaved and reloaded again matches the original file and that there is no data loss.

I'd like to agree on what makes an individual unique and ensure that we check for all of those values, with unit tests.

There are currently a lot of unit tests around this, but I'd still like more to make sure we do not lose data.

**Comment by grantwinney** [comment]
Currently, the "compare" method in the Individual class checks a few things:

* Checks if individual is null
* Compares the count and contents of names for each individual
* Compares the count and contents of events for each individual
* Compares their gender
* Compares the count and contents of notes for each individual

Are you looking for someone to build out that method, so that it tests all publicly accessible properties of an individual, such as attributes, associations, aliases, addresses, etc?

Is there anything that's not necessarily the same, such as the PermanentRecordFileNumber and AncestralFileNumber?

**Comment by RyanONeill1970** [comment]
Yes, compare all properties that will be visible to the end user of the app that uses this library. As you say, notes, names, gender, events (birth dates, death dates etc.) are there, it would be good to have the others for comparison.

What will probably happen with the equality code being updated is that the file compare tests will fail, showing where there is data loss when roundtripping the files. But that's a good thing, happy to take on those tests myself or put them in an another issue up for grabs.

I recently did some work on the notes so they should be good now, but if you have any data / tests that proves me wrong on that, would love to see it.

**Comment by grantwinney** [comment]
Sounds good. I'm getting familiar with the existing tests. Then I'll work on adding the other properties to that method, and write more tests around it as necessary to make sure I didn't break anything.

**Comment by grantwinney** [comment]
I started on this, but it seems like it might be beneficial to work on other classes that are considered part of an `Individual`.

For example, the `GedcomFamilyLink` class does not instantiate `IComparable<GedcomFamilyLink>` or `IComparable` yet, so that makes it more difficult to compare two family link instances in the `Individual` class.

I could implement those interfaces in the family link class and write some tests around the comparisons, then submit a small PR with just that class... and maybe eventually a series of PRs for the different classes.

What do you think? I could open a separate issue or reference this one in the PR(s).

**Comment by RyanONeill1970** [comment]
Yes, it sounds like you've got it figured out.
Small PRs are great, so that should be very easy to merge.
The more issues the merrier, if you label them hacktoberfest then you'll get your T-Shirt credits too.

I'm back on the code this weekend, been working on a (soon to be) open source web site that will consume this component and output reports.

**Comment by sgaulding** [comment]
@RyanONeill1970: I was working on adding some tests for checking each GedcomRecord. I wasn't if these tests are too strict and place in the correct location. As I'm new to open source work, I didn't know if this the proper venue to ask these types of questions or just open a PR.

**Comment by sgaulding** [comment]
@grantwinney: If you are already working on something similar let me know and will defer to your and @RyanONeill1970 judgement.

**Comment by RyanONeill1970** [comment]
I like what you've done @sgaulding, it may be that there is overlap with the work from @grantwinney in a few areas but I'm happy to merge it if Grant is.

Thank you Sam, much appreciated.

**Comment by grantwinney** [comment]
I think it looks good too @sgaulding. The only potential overlap I see is the `GedComComparison_GedcomFamilyLink_IsEquivalentTo_ExpectAreEqual` test, since `GedcomFamilyLink` is covered pretty thoroughly in the `GedcomFamilyLinkComparisonTest` class. You could remove that test if you want, but leaving it in won't hurt anything.

It'll be interesting to see if comparing two lists with `if (!Children.All(family.Children.Contains))` (and the similar lines comparing Events and SubmitterRecords) works as expected. Checked out the [docs](https://msdn.microsoft.com/en-us/library/bhkz42b3(v=vs.110).aspx); it looks like the class needs to implement `IEquatable<T>`.

Otherwise, but I haven't tested it yet, I'm guessing it'll compare the object references and the children (events, submitterrecords, etc) won't show as equal. But I could be wrong.

**Comment by sgaulding** [comment]
@grantwinney thanks for the suggestion of the adding IEquatable.

**Comment by grantwinney** [comment]
No problem @sgaulding. Looks good.

**Comment by grantwinney** [comment]
@RyanONeill1970 Lots of records have a `ChangeDate` on them. Do you think this is something to include in test for equality or not?

Someone could (for example) change the `Email1` property of an `Address` and then change it back to the original. Now the object as a whole is equal to the original (`Email1` is the original value again), but the `ChangeDate` was updated in the property's "setter". We should probably exclude `ChangeDate`.

**Comment by RyanONeill1970** [comment]
I don't think it should. A non technical end user would look at the visible data and see two identical records, so it's from their perspective that I was looking at this. For that reason I would not include ChangeDate in an equality comparison.
