### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#11]
The original project that this was forked from did not have any developer documentation and I'd like to build this up through XML comments.

There are a lot of junk comments (TODO and GhostDoc / nonsensical filler to remove compiler warnings) and these all need replacing with developer friendly descriptions.

Obviously, that's a lot of comments but they can be broken down into areas (individuals, events etc.).

If we can generate online documentation for this at the time of build then all the better. See http://docs.readthedocs.io/en/latest/webhooks.html

**Comment by grantwinney** [comment]
I took some time to clean up those rogue xml doc comments. I didn't get through all of them (maybe half?), but made a dent anyway. I hope it helps!

I pulled a lot of enumeration descriptions from [GenWiki](http://wiki-en.genealogy.net/GEDCOM) and [Geni](https://wiki.geni.com/index.php/GEDCOM). Didn't realize until after the fact that a lot of descriptions are already present in lists in the GedcomEvent class.

I moved some TODO statements out of the summary into the first line of whatever method they were in, which seemed to me more appropriate, but stopped after a few because I wasn't sure you'd want it.

Some random comment observations:

* There's an `<inheritdoc/>` tag on a lot of these functions, which certain tools can interpret, but which [Visual Studio seems to ignore](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3745102-add-intellisense-support-for-the-inheritdoc-ta). Not sure if that matters, if you want to eventually replace those or just leave them.

* I wasn't completely clear on what the various `Output` methods were doing, so I left those alone.

* I'm guessing that Date1, Date2, etc in GedcomDate indicate a date range, but I wasn't sure, so I left those alone too.

**Comment by RyanONeill1970** [comment]
That brilliant, very much appreciated. You are right about inheritdoc, it was just filled in by GhostDoc and was a way of me keeping coding without thinking about it. I'll stop doing that now the docs are forming.

The output methods are called by the record writer and output that particular record or sub record as a GEDCOM line. So they are for file writing.

Date ranges, you are correct. It's possible to state dates as 1910, Jan 1910 or Bet 1900 And 1901. They all come out as ranges so they can be matched later.

**Comment by grantwinney** [comment]
No problem, glad to hear it was a helpful contribution.

Now that I know I was on the right course, [I submitted one more PR](https://github.com/TheGeneGenieProject/GeneGenie.Gedcom/pull/21). (Think I'm all doc'd out for now. 😄 )

**Comment by lowenthal-jason** [comment]
I think this becomes even more important if we ever to decide to expose any of this via some kind of public API.

**Comment by RyanONeill1970** [comment]
Definitely. It's going to be usable as a library so a lot of these comments will become part of the IntelliSense.
